### PR TITLE
Development changes

### PR DESCRIPTION
**Pull request by xloem**
This branch has changes I've made that others have not reviewed or tested yet.  After some use, it's reasonable to merge it into master.

### CODE REVIEW

**Comment by xloem** [comment]
Current issue I'm running into is that b0e03644b5412e9bd9056a023f4f4d66f906f2a seems to have introduced a crash after initialising streaming [although I may have made an error bisecting].  EDIT: this issue was resolved by b7116e407f765ece0b7431020b7711ab92b6c26c

**Comment by xloem** [comment]
fixes #2

**Comment by rfdougherty** [comment]
I can confirm that the dev branch is working on OSX (Big Sur / 11.4) for a Muse S using the bleak backend and V2 viewer. Tests were done with the built-in bluetooth, so no dongle needed. E.g., to start a stream: 

`muselsl stream -b bleak -P 51 --ppg --acc --gyro`

And to view (only shows EEG channels, but I think that is expected):

`muselsl view --version 2`

Recording any stream works. E.g., to record PPG:

`muselsl record --type PPG`

**Comment by xloem** [comment]
@rfdougherty thanks so much for trying this branch out.

I was merging muse-lsl changes together because the main tree hadn't been updated in some time, but then when it became active again I stopped work on this.  Let me know if a fork of muse-lsl is still needed, and if so I can find time to bring these things together again.

**Comment by rfdougherty** [comment]
Sure, thanks for doing the bleak work! That’s the only backend that works for me. I have other wearable BLE devices that I’ll be collecting data from simultaneously with the Muse, so I think I’ll end up writing my own Muse data streamer and will just use muse-lsl for testing and quick visualization. So, your dev fork is fine for me. I did make one change to allow recording from all streams with one call. Basically just changing this line in cli.py:

        record(args.duration, args.filename, args.dejitter, args.type)

to this:

        if args.type.lower() == 'all':
            from multiprocessing import Pool
            with Pool(4) as p:
                p.starmap(record, [(args.duration, args.filename, args.dejitter, t) for t in ['EEG', 'PPG', 'ACC', 'GYRO']])
        else:
            record(args.duration, args.filename, args.dejitter, args.type)

Not sure if it’s worth a PR. If you think it is, let me know and I’ll submit one.

From: xloem ***@***.***>
Date: Friday, July 23, 2021 at 2:52 AM
To: xloem/muse-lsl ***@***.***>
Cc: Robert Dougherty ***@***.***>, Mention ***@***.***>
Subject: Re: [xloem/muse-lsl] Development changes (#12)

@rfdougherty<https://github.com/rfdougherty> thanks so much for trying this branch out.

I was merging muse-lsl changes together because the main tree hadn't been updated in some time, but then when it became active again I stopped work on this. Let me know if a fork of muse-lsl is still needed, and if so I can find time to bring these things together again.

**Comment by xloem** [comment]
If you could submit a PR to the main project at https://github.com/alexandrebarachant/muse-lsl that would be great.

I'll add you to this repository, too; feel free to merge things in if they're of stable, reliable quality, etc.

**Comment by xloem** [comment]
To visitors: this repository was a fork of muse-lsl I was planning to maintain if the muse-lsl maintainers didn't respond.

They have since merged most (not all) of these patches into their upstream, and this repository could be reset to the content of that one.  All the patches were taken from their pull requests.

The upstream muse-lsl maintainers are still very slow to respond, and not very active, so this repository still has some value.

**Comment by buyuk-dev** [comment]
Changes look good, did some basic testing and synced with upstream so i think it can be merged now.

I will continue working with it so in case of problems i can take responsibility for fixing them in a short time.

**Pull request merged**
